### ISSUE TITLE
建议项目名称使用全部小写字母，连字符连接

### ISSUE THREAD

**Issue by blankhua** [zhangxinxu/ieBetter.js#3]
建议项目名称改为 `ie-better.js`。

理由：不是所有操作系统都可以识别 URL 中的大小写，比如 Windows 就不可以，所以建议所有可能在 URL 中出现的字符，全部使用小写。然后 Google 推荐连字符（-），不建议下划线（_），所以 `ie-better.js` 可能会更好一些。

**Comment by dancinglone** [comment]
只要同一路径没有iebetter.js, ieBetter.js应该不会有问题吧？
