### ISSUE TITLE
IE8下报错

### ISSUE THREAD

**Issue by latel** [zhangxinxu/ieBetter.js#5]
'eventType' is undefined
ieBetter.js, line 354 character 5

**Comment by MaleDong** [comment]
Yes, this is really a bug, I temporarily fixed that by re-writing this function:

global.removeEventListener = function(eventType, funcHandle, useCapture*) {
				oDomExtend.removeEventListener.call(global, eventType, funcHandle, useCapture);	
			};

Notice that "removeEventListener" function ,we need to pass the parameters there. You can open the file and do what I said, however, the final result just waits the owner to fix, maybe he will find a better solution;)

**Comment by pptoon** [comment]
@MaleDong thank you 梅冬，are you a programmer now? and many years ago ,i heard you were a tv newsreporter.

**Comment by MaleDong** [comment]
No. I began my experience of a programmer since 2009 for background mainly

**Comment by zhangxinxu** [comment]
@MaleDong thank you
