### ISSUE TITLE
Create package.json for package informateion

### ISSUE THREAD

**Issue by Piicksarn** [zhangxinxu/ieBetter.js#6]
Hi, @zhangxinxu 

Your great work had been recommend being added in [cdnjs](https://github.com/cdnjs/cdnjs).
However, we need more confirmed information when include it in our project.
Would you mind to add **`package.json`** for the package :)?
And we would appreciate your help. [#5737](https://github.com/cdnjs/cdnjs/issues/5737)

Thank you!
Piicksarn

**Comment by zhangxinxu** [comment]
OK,  thanks~ hold a minute~

**Comment by zhangxinxu** [comment]
done!

**Comment by Piicksarn** [comment]
Thank you!

**Comment by hax** [comment]
@zhangxinxu 唔，还以为你已经弃坑了
